### PR TITLE
Test to remove all outline rule, nix shadows. Fixes #84

### LINKED ISSUE #84: Leave default outline for focus, handle as exceptions on projects
The `outline:none` rule makes it impossible to get the clearer, native outline back on inputs, checks, radios, and buttons. I think we should try removing nay of these rules and get rid of the shadow-based focus styles so we have s simpler default

### PR DESCRIPTION
**Pull request by toddparker**
This isn't ready for primetime, I see custom selects don't look good and I didn't hit all the inputs
http://84.origin.formcore.fgview.com/

### CODE REVIEW

**Comment by zachleat** [comment]
Hmm, @toddparker here are my notes for this one

In favor of this change:

* formcore had different focus styles for inputs and selects before: 
image

Pain points if we wanted to do a more consistent focus style:

* The selects don’t look good because select-css uses it internally (uses a wrapper element to emulate the focus style, given that in some browsers we use a > 100% width select inside of the wrapper to hide the arrow).
* Removing this switches from an `inset` box-shadow to something that seems to be both inset and outset
* Because the outline is now both inset and outset, politespace wrapper elements clip the outline (Chrome):
image vs 
image We could potentially use a negative `outline-offset` to move to a more inset version
* Firefox only has a blue border change on focus (no other focus style applied, not sure if this is obvious enough): 
image

**Comment by toddparker** [comment]
@zachleat - yeah, the custom select is a tricky one for sure but if we can make it look more like the native outline for buttons, even if faked in CSS, that might be good

native select:
image

vs. native button
image


...they are pretty much the same

**Comment by zachleat** [comment]
Hmm, ok. I did a little bit more research and found some things that are _close_ but not quite. In Mac OS those colors are actually part of the OS preferences (I assume something similar exists for other operating systems):

image

Looks like `-webkit-focus-ring-color` might be somewhat close:

Chrome (native focus on right):
image
Safari  (native focus on right):
image

Firefox seems to respect the `Highlight` system color:
image

and Firefox with `-moz-mac-focusring`:
image

(via https://developer.mozilla.org/en-US/docs/Web/CSS/Mozilla_Extensions)

Looks like all of them use the `Appearance` OS setting though, which does not match what the browser is doing for normal focus outline colors (which seems to be the highlight color)

**Comment by zachleat** [comment]
This is probably ok to merge Todd if you want to have another look: http://84.origin.formcore.fgview.com/

**Comment by toddparker** [comment]
@zachleat - This feels solid except...

the cc field seems to have the older focus style:
image

double bottom border on error
image

**Comment by zachleat** [comment]
@toddparker The CC field has the default style, however as mentioned above, it’s being clipped by `overflow: hidden` on the politespace wrapper. I’ll create an upstream ticket for this in politespace because I’m not sure that property is necessary any more, but I’ll have to look closer at the test cases.

Double border thing is fixed now.

**Pull request merged**
